<%
'--------------------
'Declare variables
	
	Dim libro
	Dim cap
	Dim vers_num
	Dim vers_txt
	'Dim boolSortBy
	'Dim id_value
	'Dim id_field
	'Dim firstNumberLink
	'Dim lastNumberLink
	'Dim strTrimSize
	'Dim strLineScreen
	'Dim dtmPublicationDueDate
	'Dim strPublicationIssueDate
	'Dim strPublicationCompany
	'Dim strFundingAmount
	'Dim strPublicationName
	'Dim strProjectCost
	'Dim strProductionTime
	'Dim strMktMatChildName
	'Dim strDeliverableSpecs
	'Dim strOdenOrderID
	'Dim cmbAssocShippingCountry
	'Dim cmbAssocShippingState
	'Dim strFedExAccountNum
	'Dim strAssocShippingTitle
	'Dim strAssocShippingPhone
	'Dim strAssocShippingFax
	'Dim strAssocShippingExt
	'Dim strAssocShippingCountry
	'Dim strAssocShippingStateOther
	'Dim strAssocShippingZip
	'Dim strAssocShippingState
	'Dim strAssocShippingCity
	'Dim strAssocShippingAddress2
	'Dim strAssocShippingAddress1
	'Dim strAssocShippingLName
	'Dim strAssocShippingFName
	'Dim imgShim
	'Dim OrderID
	'Dim strForDownloadChecked1
	'Dim strForDownloadChecked2
	'Dim boolAssociateThumbNailFile
	'Dim boolAssociatePDFFile
	'Dim strPDFchecked1
	'Dim strPDFchecked2
	'Dim strThumbNailchecked1
	'Dim strThumbNailchecked2
	'Dim strMktMatGrandChildPDF
	'Dim strMktMatGrandChildThumbnail
	'Dim numTimePrinting1
	'Dim numTimePrinting2
	'Dim numTimePrinting3
	'Dim numTimePrinting4
	'Dim numTimePrinting5
	'Dim numTimePrinting6
	'Dim numTimeDiskProof
	'Dim strCostCustPrinting1
	'Dim strCostCustPrinting2
	'Dim strCostCustPrinting3
	'Dim strCostCustPrinting4
	'Dim strCostCustPrinting5
	'Dim strCostCustPrinting6
	'Dim strCostPrintingOnly1
	'Dim strCostPrintingOnly2
	'Dim strCostPrintingOnly3
	'Dim strCostPrintingOnly4
	'Dim strCostPrintingOnly5
	'Dim strCostPrintingOnly6
	'Dim strCostCustDiskProof
	'Dim strCostCustFilmProof
	'Dim strDescriptor1
	'Dim strDescriptor2
	'Dim strDescriptor3
	Dim buildOptions
	'Dim MktMatChildID
	'Dim MktMatChildrenOptions
	'Dim strMktMatGrandChildName
	'Dim strMktMatGrandChildDescription
	'Dim IDfield
	'Dim boolAudienceAll
	'Dim boolAudienceAssocBest
	'Dim boolAudienceAMF
	'Dim boolAudienceAssocBetter
	'Dim boolAudienceViewers
	'Dim boolAudienceFedEx
	'Dim strAudienceAllState
	'Dim strAudienceAssocBestState
	'Dim strAudienceAMFState
	'Dim strAudienceAssocBetterState
	'Dim strAudienceViewersState
	'Dim strAudienceFedExState
	'Dim cmbTierLevelID
	'Dim strFAQQuestion
	'Dim strFAQAnswer
	'Dim FAQID
	'Dim thisItem
	'Dim which_profiles
	'Dim strProfileName
	'Dim actionWord
	'Dim firstRecordThisPage
	'Dim ContactID
	'Dim strProfileTypeFull
	'Dim strProfileType
	'Dim actionButnWord
	'Dim butnAddValue
	'Dim butnDeleteValue
	'Dim submitButn
	'Dim deleteButn
	'Dim cancelButn
	'Dim strAssocAcronym
	'Dim strBudget
	'Dim boolFedExExpress
	'Dim boolFedExGround
	'Dim boolFedExHome
	'Dim strFedExExpressDiscount
	'Dim strFedExGroundDiscount
	'Dim strFedExHomeDiscount
	'Dim strNatlAcctCodeExpress
	'Dim strNatlAcctCodeGround
	'Dim strNatlAcctCodeHome
	'Dim strExpressSubGroupNums
	'Dim strAccessLevelName
	'Dim accessLevelOptions
	'Dim accessLevelRadios
	'Dim action
	'Dim actionHREF
	'Dim actionHREF_End
	'Dim addAssocbullet			
	'Dim admin
	'Dim admin_bullet
	'Dim adminLink
	'Dim adminURL
	'Dim AlreadyInDB
	'Dim anumcols
	'Dim approx_cost
	'Dim areaCode
	'Dim assoc_CurrentNumEnrolled
	'Dim assoc_membership_size
	'Dim assocID
	'Dim Attempted
	'Dim badChar
	Dim bc	
	'Dim bday
	'Dim bgcolor1
	'Dim bgcolor2
	Dim bibliaName
	Dim bibliaOtra
	Dim bibliaValera
	Dim bibliaJerusalen
	Dim bibliaModerna
	'Dim bmonth
	'Dim Body
	'Dim bullet
	'Dim cday
	'Dim cellbgcolor
	'Dim cellbgcolor2
	'Dim cmbCountry
	'Dim cmbState
	'Dim cmonth
	'Dim coll
	'Dim collateralURL
	'Dim company
	'Dim contact_bullet
	'Dim contactURL
	'Dim Count
	'Dim counter
	'Dim countryOptions
	'Dim CurrentNumEnrolledOptions
	'Dim custnum
	'Dim dateEnrolled
	'Dim DateEntered
	'Dim dateofbirth
	Dim DB
	'Dim deleteValue
	'Dim descrip_1
	'Dim descrip_2
	'Dim descrip_3
	'Dim dimfields
	'Dim downbullet
	'Dim dropdate
	'Dim adminEditAssocbullet
	'Dim editmyAssocbullet
	'Dim endLink
	'Dim enrollmentFormURL
	'Dim eResourcesURL
	'Dim ErrorMessageAlready
	'Dim errorMsg
	'Dim exception1
	'Dim exception10
	'Dim exception11
	'Dim exception2
	'Dim exception3
	'Dim exception4
	'Dim exception5
	'Dim exception6
	'Dim exception7
	'Dim exception8
	'Dim exception9
	'Dim faq_bullet
	'Dim faqURL
	'Dim fieldcount
	Dim Fields
	'Dim file
	'Dim FileName
	'Dim fiveyears
	'Dim FolderPath
	Dim fontcolor
	'Dim forgotpass
	'Dim formaction
	'Dim FSO
	'Dim fullname
	'Dim getpassword
	'Dim headline
	'Dim homeURL
	'Dim http_host
	Dim i
	Dim iCount
	'Dim idate
	'Dim iday
	Dim IE
	'Dim imonth
	'Dim info_required
	'Dim instructions
	'Dim interest
	Dim Item
'	'Dim MktMatParentID
'	'Dim MktMatParentAbbrv
'	'Dim MktMatParentDescrip
'	'Dim MktMatParentName
'	'Dim MktMatChildID
'	'Dim MktMatChildAbbrv
'	'Dim MktMatChildDescrip
'	'Dim MktMatChildName
	'Dim ItemKey
	'Dim iyear
	'Dim j
	'Dim lastcomma
	'Dim login
	'Dim login_bullet
	'Dim loginURL
	'Dim logoff
	'Dim logoff_bullet
	'Dim logoffURL
	'Dim loremIpsum
	'Dim loremIpsumShort
	Dim Lynx
	'Dim mailsender
	'Dim mailserver
	'Dim mailsubject 
	'Dim MaterialListing
	'Dim materialListingDescriptions
	'Dim maxcounter
	'Dim membershipOptions
	'Dim membershipOptions2
	'Dim midname
	'Dim mkt_bullet
	'Dim mktmatLinks
	'Dim mktURL
	'Dim msg
	'Dim msg1
	'Dim msg2
	'Dim my_bgcolor
	'Dim myarray
	'Dim Name
	'Dim newfax
	'Dim newPhone
	'Dim NotApproved
	'Dim numAccessLevel
	Dim numcol
	Dim numcols
	Dim numcols2
	Dim numcols3
	Dim numcols4
	Dim numcols5
	Dim numcols6
	Dim numcols7
	'Dim numCurrentNumEnrolled 
	'Dim numMembershipSize
	'Dim objConn
	'Dim objEMail
	Dim objRec
	'Dim objsmtp
	Dim Opera
	'Dim orderby
	'Dim orderURL
	'Dim orderwizURL
	'Dim pagetitle
	'Dim passwdtype
	'Dim path_info
	'Dim phnFax
	'Dim phnPhone
	'Dim phone2
	'Dim phonePrefix
	'Dim phoneSuffix
	'Dim pos
	'Dim prefix
	'Dim printAdsURL
	'Dim profile_bullet
	'Dim profileURL
	'Dim progbenefits_bullet
	'Dim progBenefitsURL
	'Dim rCount
	'Dim Rejected
	'Dim SCRIPT_NAME
	'Dim search_bullet
	'Dim searchURL
	'Dim secondTry
	'Dim selected1
	'Dim selected2
	'Dim selected3
	'Dim selected4
	'Dim selected5
	'Dim selected6
	'Dim selected7
	'Dim serverName
	'Dim shipmgrURL
	'Dim shipsmart_bullet
	'Dim shipSmartURL
	'Dim shortSiteName
	'Dim showpwd
	'Dim sidebullet
	'Dim sitename
	'Dim sql
	'Dim sql2
	'Dim sql3
	'Dim sql4
	'Dim sql5
	'Dim sqlWhere
	'Dim sqlWhere2
	'Dim stateOptions
	'Dim stationeryURL
	'Dim strAddress1
	'Dim strAddress2
	'Dim strAssocName
	'Dim strCity
	'Dim strEmail
	'Dim strExt
	'Dim strFirstname
	'Dim strLastname
	'Dim strLogoImg
	'Dim strPassword
	Dim strSQL
	'Dim strStateOther
	'Dim strTitle
	'Dim strZip
	'Dim SubComplete
	'Dim submit
	'Dim submitvalue
	Dim tablename
	Dim tdclass
	'Dim thisAccessLevel
	'Dim thisbullet
	'Dim thisPage
	'Dim thisyear
	'Dim titleImg
	'Dim Upload
	'Dim uploadAction
	'Dim uploadMsg
	'Dim URL
	Dim urlPath
	'Dim urltogo
	'Dim userid
	'Dim UserName
	'Dim usr
	'Dim ValidAdminID
	'Dim years
%>